"use client";
import { useEffect, useMemo, useState } from "react";
import productsData from "./data/products.json";
type Product=typeof productsData[number]; type CartLine={product:Product;qty:number}; const products=productsData as Product[];
export default function Home(){
 const[category,setCategory]=useState("All Products"),[query,setQuery]=useState(""),[cart,setCart]=useState<CartLine[]>([]),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[sent,setSent]=useState("");
 const[videos,setVideos]=useState<{id:string;title:string;category:string;src:string}[]>([]);
 const[form,setForm]=useState({name:"",phone:"",company:"",note:""});
 const categories=useMemo(()=>["All Products",...Array.from(new Set(products.map(p=>p.category)))],[]);
 const visible=useMemo(()=>products.filter(p=>(category==="All Products"||p.category===category)&&`${p.name}${p.subcategory}${p.specs}`.toLowerCase().includes(query.toLowerCase())),[category,query]);
 const total=cart.reduce((s,l)=>s+l.product.price*l.qty,0);
 useEffect(()=>{const saved=localStorage.getItem("copina-cart");if(saved)setCart(JSON.parse(saved));fetch("/api/videos").then(r=>r.ok?r.json():Promise.reject()).then(data=>setVideos(data.videos||[])).catch(()=>undefined)},[]); useEffect(()=>localStorage.setItem("copina-cart",JSON.stringify(cart)),[cart]);
 function add(product:Product){setCart(lines=>{const found=lines.find(l=>l.product.id===product.id);return found?lines.map(l=>l.product.id===product.id?{...l,qty:l.qty+1}:l):[...lines,{product,qty:1}]});setCartOpen(true)}
 function change(id:string,delta:number){setCart(lines=>lines.map(l=>l.product.id===id?{...l,qty:l.qty+delta}:l).filter(l=>l.qty>0))}
 async function submit(e:React.FormEvent){e.preventDefault();const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customer:form,items:cart.map(l=>({id:l.product.id,name:l.product.name,price:l.product.price,qty:l.qty,mode:l.product.orderMode})),total})});const data=await response.json();if(!response.ok)return setSent(data.error||"Submission failed. Please try again.");setSent(`Your request has been submitted. Reference: ${data.orderId}`);setCart([]);setCheckout(false)}
 return <main><style>{`.video-section{margin-bottom:90px}.video-section .video-strip{margin-bottom:0}.video-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:20px}.video-grid article{background:#fff;border-radius:12px;overflow:hidden;padding-bottom:16px}.video-grid video{width:100%;aspect-ratio:16/9;background:#111}.video-grid h3,.video-grid small{display:block;margin:8px 16px}.video-grid small{color:#718077}@media(max-width:900px){.video-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.video-grid{grid-template-columns:1fr}}`}</style><header className="nav shell"><a className="brand" href="#top"><span className="brand-mark">C</span><span>COPINA</span></a><nav><a href="#products">Products</a><a href="#videos">Product Videos</a><a href="#contact">Contact Us</a></nav><button className="cart-button" onClick={()=>setCartOpen(true)}>Purchase List <b>{cart.reduce((s,l)=>s+l.qty,0)}</b></button></header>
 <section className="hero shell" id="top"><div><p className="eyebrow">COMMERCIAL KITCHEN EQUIPMENT</p><h1>Professional kitchen solutions,<br/><em>designed for efficient operations.</em></h1><p>COPINA provides commercial kitchen and restaurant design, professional equipment supply, installation guidance and after-sales support for customers in Saudi Arabia, the UAE and African markets.</p><div className="hero-actions"><a className="primary" href="#products">Browse Products</a><a className="ghost" href="#contact">Request a Solution</a></div><div className="stats"><span><b>50</b>Selected Products</span><span><b>9</b>Specialist Categories</span><span><b>20</b>Verified Product Images</span></div></div><div className="hero-showcase"><img src="/products/1024136394235.jpg" alt="Commercial ultrasonic dishwasher"/><span>Commercial Kitchen Solutions</span></div></section>
 <section className="products shell" id="products"><div className="section-head"><div><p className="eyebrow">PRODUCT CATALOG</p><h2>Product Showcase</h2></div><label className="search">Search Products<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, category or specification"/></label></div><div className="filters">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><p className="count">{visible.length} products found</p><div className="product-grid">{visible.map(product=><article className="product-card" key={product.id}><div className="product-image">{product.image?<img src={product.image} alt={product.name}/>:<div className="pending"><span>C</span><p>Product image coming soon</p></div>}<span className="tag">{product.subcategory}</span></div><div className="product-body"><small>{product.category} · ID {product.id}</small><h3>{product.name}</h3><p className="specs">{product.specs}</p><div className="product-bottom"><div><span>Reference Price</span><strong>¥{product.price.toLocaleString("en-US",{minimumFractionDigits:2})}</strong></div>{product.orderMode==="Order Online"?<button onClick={()=>add(product)}>Add to Purchase List</button>:<button className="outline" onClick={()=>{add(product);setCheckout(true)}}>Request a Quote</button>}</div></div></article>)}</div></section>
 <section className="video-section shell" id="videos"><div className="video-strip"><div><p className="eyebrow">PRODUCT VIDEOS</p><h2>See the equipment. Understand the value.</h2><p>Explore equipment demonstrations, installation guidance and operating videos.</p></div><a className="primary" href="#contact">Contact Us to Add a Video</a></div>{videos.length>0&&<div className="video-grid">{videos.map(v=><article key={v.id}><video src={v.src} controls preload="metadata"/><small>{v.category}</small><h3>{v.title}</h3></article>)}</div>}</section>
 <footer id="contact"><div className="shell"><div className="brand"><span className="brand-mark">C</span><span>COPINA</span></div><p>Commercial kitchen design, equipment supply, installation guidance and after-sales support.</p><span>© 2026 COPINA</span></div></footer>
 {cartOpen&&<div className="drawer-backdrop" onMouseDown={()=>setCartOpen(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" aria-label="Close purchase list" onClick={()=>setCartOpen(false)}>×</button><p className="eyebrow">PURCHASE LIST</p><h2>Purchase List</h2>{sent&&<p className="success">{sent}</p>}{cart.length===0?<div className="empty">Your purchase list is empty.</div>:<><div className="cart-lines">{cart.map(line=><div className="cart-line" key={line.product.id}><div><b>{line.product.name}</b><span>¥{line.product.price.toFixed(2)}</span></div><div className="qty"><button aria-label="Decrease quantity" onClick={()=>change(line.product.id,-1)}>−</button><span>{line.qty}</span><button aria-label="Increase quantity" onClick={()=>change(line.product.id,1)}>＋</button></div></div>)}</div><div className="cart-total"><span>Estimated Total</span><strong>¥{total.toLocaleString("en-US",{minimumFractionDigits:2})}</strong></div>{!checkout?<button className="primary full" onClick={()=>setCheckout(true)}>Enter Order Details</button>:<form className="checkout" onSubmit={submit}><input required placeholder="Contact name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="Phone or WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Company name (optional)" value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/><textarea placeholder="Delivery address, quantity or other requirements" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><button className="primary full" type="submit">Submit Order / Enquiry</button><small>Our sales team will confirm availability, freight, taxes and the final price after submission.</small></form>}</>}</aside></div>}</main>}
