"use client";
import { useEffect, useMemo, useState } from "react";
import productsData from "./data/products.json";
type Product=typeof productsData[number]; type CartLine={product:Product;qty:number}; const products=productsData as Product[];
export default function Home(){
 const[category,setCategory]=useState("全部产品"),[query,setQuery]=useState(""),[cart,setCart]=useState<CartLine[]>([]),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[sent,setSent]=useState("");
 const[videos,setVideos]=useState<{id:string;title:string;category:string;src:string}[]>([]);
 const[form,setForm]=useState({name:"",phone:"",company:"",note:""});
 const categories=useMemo(()=>["全部产品",...Array.from(new Set(products.map(p=>p.category)))],[]);
 const visible=useMemo(()=>products.filter(p=>(category==="全部产品"||p.category===category)&&`${p.name}${p.subcategory}${p.specs}`.toLowerCase().includes(query.toLowerCase())),[category,query]);
 const total=cart.reduce((s,l)=>s+l.product.price*l.qty,0);
 useEffect(()=>{const saved=localStorage.getItem("copina-cart");if(saved)setCart(JSON.parse(saved));fetch("/api/videos").then(r=>r.ok?r.json():Promise.reject()).then(data=>setVideos(data.videos||[])).catch(()=>undefined)},[]); useEffect(()=>localStorage.setItem("copina-cart",JSON.stringify(cart)),[cart]);
 function add(product:Product){setCart(lines=>{const found=lines.find(l=>l.product.id===product.id);return found?lines.map(l=>l.product.id===product.id?{...l,qty:l.qty+1}:l):[...lines,{product,qty:1}]});setCartOpen(true)}
 function change(id:string,delta:number){setCart(lines=>lines.map(l=>l.product.id===id?{...l,qty:l.qty+delta}:l).filter(l=>l.qty>0))}
 async function submit(e:React.FormEvent){e.preventDefault();const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customer:form,items:cart.map(l=>({id:l.product.id,name:l.product.name,price:l.product.price,qty:l.qty,mode:l.product.orderMode})),total})});const data=await response.json();if(!response.ok)return setSent(data.error||"提交失败，请稍后重试");setSent(`订单已提交，编号 ${data.orderId}`);setCart([]);setCheckout(false)}
 return <main><style>{`.video-section{margin-bottom:90px}.video-section .video-strip{margin-bottom:0}.video-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:20px}.video-grid article{background:#fff;border-radius:12px;overflow:hidden;padding-bottom:16px}.video-grid video{width:100%;aspect-ratio:16/9;background:#111}.video-grid h3,.video-grid small{display:block;margin:8px 16px}.video-grid small{color:#718077}@media(max-width:900px){.video-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.video-grid{grid-template-columns:1fr}}`}</style><header className="nav shell"><a className="brand" href="#top"><span className="brand-mark">C</span><span>COPINA</span></a><nav><a href="#products">产品中心</a><a href="#videos">产品视频</a><a href="#contact">联系我们</a></nav><button className="cart-button" onClick={()=>setCartOpen(true)}>采购清单 <b>{cart.reduce((s,l)=>s+l.qty,0)}</b></button></header>
 <section className="hero shell" id="top"><div><p className="eyebrow">COMMERCIAL KITCHEN EQUIPMENT</p><h1>专业厨房设备，<br/><em>为高效运营而生。</em></h1><p>从制冷、洗涤到食品加工，COPINA 为酒店、餐厅与中央厨房提供可靠的一站式设备选择。</p><div className="hero-actions"><a className="primary" href="#products">浏览产品</a><a className="ghost" href="#contact">获取方案</a></div><div className="stats"><span><b>50</b>精选产品</span><span><b>9</b>专业分类</span><span><b>20</b>合规产品图</span></div></div><div className="hero-showcase"><img src="/products/1024136394235.jpg" alt="商用超声波洗碗机"/><span>商用厨房解决方案</span></div></section>
 <section className="products shell" id="products"><div className="section-head"><div><p className="eyebrow">PRODUCT CATALOG</p><h2>产品展示区</h2></div><label className="search">搜索产品<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入名称、分类或规格"/></label></div><div className="filters">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><p className="count">找到 {visible.length} 个产品</p><div className="product-grid">{visible.map(product=><article className="product-card" key={product.id}><div className="product-image">{product.image?<img src={product.image} alt={product.name}/>:<div className="pending"><span>C</span><p>产品图片整理中</p></div>}<span className="tag">{product.subcategory}</span></div><div className="product-body"><small>{product.category} · ID {product.id}</small><h3>{product.name}</h3><p className="specs">{product.specs}</p><div className="product-bottom"><div><span>网页参考价</span><strong>¥{product.price.toLocaleString("zh-CN",{minimumFractionDigits:2})}</strong></div>{product.orderMode==="在线下单"?<button onClick={()=>add(product)}>加入采购单</button>:<button className="outline" onClick={()=>{add(product);setCheckout(true)}}>在线询价</button>}</div></div></article>)}</div></section>
 <section className="video-section shell" id="videos"><div className="video-strip"><div><p className="eyebrow">PRODUCT VIDEOS</p><h2>看见设备，理解价值。</h2><p>已上传的设备演示、安装与使用视频继续保留。</p></div><a className="primary" href="#contact">上传新视频请联系我们</a></div>{videos.length>0&&<div className="video-grid">{videos.map(v=><article key={v.id}><video src={v.src} controls preload="metadata"/><small>{v.category}</small><h3>{v.title}</h3></article>)}</div>}</section>
 <footer id="contact"><div className="shell"><div className="brand"><span className="brand-mark">C</span><span>COPINA</span></div><p>专业商用厨房设备产品目录</p><span>© 2026 COPINA</span></div></footer>
 {cartOpen&&<div className="drawer-backdrop" onMouseDown={()=>setCartOpen(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setCartOpen(false)}>×</button><p className="eyebrow">PURCHASE LIST</p><h2>采购清单</h2>{sent&&<p className="success">{sent}</p>}{cart.length===0?<div className="empty">采购清单还是空的</div>:<><div className="cart-lines">{cart.map(line=><div className="cart-line" key={line.product.id}><div><b>{line.product.name}</b><span>¥{line.product.price.toFixed(2)}</span></div><div className="qty"><button onClick={()=>change(line.product.id,-1)}>−</button><span>{line.qty}</span><button onClick={()=>change(line.product.id,1)}>＋</button></div></div>)}</div><div className="cart-total"><span>参考合计</span><strong>¥{total.toLocaleString("zh-CN",{minimumFractionDigits:2})}</strong></div>{!checkout?<button className="primary full" onClick={()=>setCheckout(true)}>填写订单信息</button>:<form className="checkout" onSubmit={submit}><input required placeholder="联系人姓名" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="电话或微信" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="公司名称（选填）" value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/><textarea placeholder="交货地址、数量或其他需求" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><button className="primary full" type="submit">提交订单/询价</button><small>提交后由销售人员确认库存、运费、税费和最终成交价。</small></form>}</>}</aside></div>}</main>}
